name: leo_env
channels:
  - conda-forge
  - defaults
dependencies:
  # 1. Use Python 3.12 (The current "Gold Standard" for compatibility)
  - python=3.12

  # 2. Core Scientific Stack (Conda handles the heavy math optimization)
  - numpy>=1.26   # Flexible to allow Windows/Linux differences
  - pandas>=2.0
  - scipy
  - matplotlib
  - astropy
  - xarray
  - numba
  - numexpr
  - bottleneck

  # 3. GUI / Tools
  - pyqt
  - pillow
  - tornado
  - tqdm
  - pyyaml
  - requests
  - packaging

  # 4. The "Pip Fallback" Strategy
  # We install these via Pip to get the latest versions on Windows
  - pip
  - pip:
      # Pyshtools on Pip supports Windows Python 3.12 @ v4.13.1
      - pyshtools>=4.13
      
      # Other specific pip packages
      - pyatmos
      - pymsis
      - wget
      - pooch
      - sgp4
      - skyfield
      - jplephem